#!/bin/bash

function huong_dan() {
  WPTangToc OLS có tính năng tắt XML-RPC WordPress, thì đây là một biện pháp bảo mật và tối ưu hóa quan trọng, giúp bạn vô hiệu hóa tệp xmlrpc.php trên các website WordPress của mình.

  XML-RPC là gì?
  * xmlrpc.php là một tệp tin trong WordPress, hoạt động như một Giao diện Lập trình Ứng dụng [API]. Nó cho phép các ứng dụng và dịch vụ bên ngoài kết nối và thực hiện các hành động trên website WordPress của bạn từ xa [ví dụ: đăng bài từ điện thoại, nhận thông báo pingback/trackback, kết nối với các dịch vụ như Jetpack].

  🎯 Tại sao cần tắt XML-RPC?
  * Tăng cường Bảo mật: Đây là lý do chính. xmlrpc.php là một mục tiêu tấn công rất phổ biến:
  * Tấn công Brute-Force: Kẻ tấn công có thể thử hàng ngàn mật khẩu qua xmlrpc.php để dò tài khoản admin.
  * Tấn công DDoS [Khuếch đại]: Lợi dụng tính năng pingback để tấn công các website khác.
  * Quét và Thu thập Thông tin: Bị lợi dụng để tìm kiếm người dùng hoặc thông tin khác.
  * Giảm tải Server: Vô hiệu hóa xmlrpc.php giúp ngăn chặn các truy cập không mong muốn từ bot và kẻ tấn công, giảm bớt gánh nặng không cần thiết cho máy chủ.
  * Không còn Cần thiết: Với sự phát triển của REST API trong WordPress, nhiều chức năng của XML-RPC đã trở nên lỗi thời hoặc ít được sử dụng đối với nhiều website hiện đại.

  Tóm lại: Tính năng tắt xmlrpc.php trong WPTangToc OLS là một công cụ hữu ích giúp bạn gia cố bảo mật và giảm tải cho website WordPress bằng cách loại bỏ một cổng giao tiếp thường bị lợi dụng để tấn công. Đây là một trong những bước bảo mật cơ bản được khuyến nghị cho hầu hết các website WordPress hiện nay, miễn là bạn không còn phụ thuộc vào các chức năng của XML-RPC.
}

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý WordPress => Tắt xml-rpc WordPress                              |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lựa chọn website bạn muốn tắt xml-rpc WordPress: "
echo ""
lua_chon_NAME

. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

. /etc/wptt/vhost/."$NAME".conf

pathcheckplugin="/usr/local/lsws/$NAME/html/wp-content/plugins/xml-rpc-wptangtoc"
if [[ -d "$pathcheckplugin" ]]; then
  echoDo "ban da kich hoat tat xml-rpc wordpress roi"
  . /etc/wptt/wptt-wordpress-main 1
fi

read -p "Bạn muốn tắt xml rpc wordpress (y/n): " check
if [[ "$check" = "y" ]]; then
  . /etc/wptt/php/php-cli-domain-config $NAME

  _runing "Tắt xml rpc WordPress cho website $NAME"
  chown -R "$User_name_vhost":"$User_name_vhost" /usr/local/lsws/"$NAME"/html/wp-content/plugins/xml-rpc-wptangtoc
  cd /usr/local/lsws/"$NAME"/html/wp-content/plugins/xml-rpc-wptangtoc && find . -type d -exec chmod 755 {} \;
  cd /usr/local/lsws/"$NAME"/html/wp-content/plugins/xml-rpc-wptangtoc && find . -type f -exec chmod 644 {} \;
  _rundone "Tắt xml rpc WordPress cho website $NAME"
fi
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi
