#!/bin/bash

if [[ $wptangtocols_version = "" ]];then
wptangtocols_version=$(curl -s https://raw.githubusercontent.com/wptangtoc/wptangtoc-ols/refs/heads/main/version-wptangtoc-ols.txt)
fi

if [[ $wptangtocols_version ]];then
echo "$wptangtocols_version" > /tmp/wptangtoc-ols-version
fi
