#!/bin/bash
# @author: Gia Tuấn
# @since: 2025

. /etc/wptt/echo-color

echo "=========================================="
echo "  WPTangToc OLS - Laravel wptt-laravel-packages        "
echo "=========================================="
echo ""
echoDo "Tính năng này đang được phát triển"
echo "Sẽ được tích hợp trong phiên bản tiếp theo"

